"""is_superuser flag

Revision ID: a4ef50f08e69
Revises: 7b45f6e99368
Create Date: 2026-04-26 01:04:26.360232+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ef50f08e69'
down_revision: Union[str, None] = '7b45f6e99368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add with a server_default so existing rows backfill to FALSE, then drop
    # the default so future inserts must set the value explicitly via the ORM.
    op.add_column(
        'users',
        sa.Column('is_superuser', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.alter_column('users', 'is_superuser', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###
