"""onboarding and growth dna

Revision ID: 66e7e6ee9578
Revises: 75b345cf7a41
Create Date: 2026-04-25 21:03:32.707874+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66e7e6ee9578'
down_revision: Union[str, None] = '75b345cf7a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('offer_description', sa.Text(), nullable=True),
    sa.Column('pain_points', sa.Text(), nullable=True),
    sa.Column('primary_conversion_goal', sa.String(length=120), nullable=True),
    sa.Column('monthly_ad_budget_usd', sa.Integer(), nullable=True),
    sa.Column('geographic_target', sa.Text(), nullable=True),
    sa.Column('current_ad_platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('landing_page_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analytics_status', sa.String(length=32), nullable=True),
    sa.Column('competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('brand_voice', sa.Text(), nullable=True),
    sa.Column('step_completed', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_onboarding_profiles_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_profiles'))
    )
    op.create_index(op.f('ix_onboarding_profiles_workspace_id'), 'onboarding_profiles', ['workspace_id'], unique=True)
    op.create_table('growth_dna_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('onboarding_profile_id', sa.UUID(), nullable=False),
    sa.Column('business_summary', sa.Text(), nullable=False),
    sa.Column('icp_summary', sa.Text(), nullable=False),
    sa.Column('offer_positioning', sa.Text(), nullable=False),
    sa.Column('funnel_readiness_score', sa.Integer(), nullable=False),
    sa.Column('paid_ads_readiness_score', sa.Integer(), nullable=False),
    sa.Column('seo_geo_opportunity_summary', sa.Text(), nullable=False),
    sa.Column('website_conversion_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tracking_readiness', sa.Text(), nullable=False),
    sa.Column('recommended_first_campaigns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thirty_day_growth_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_profile_id'], ['onboarding_profiles.id'], name=op.f('fk_growth_dna_profiles_onboarding_profile_id_onboarding_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_growth_dna_profiles_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_dna_profiles'))
    )
    op.create_index(op.f('ix_growth_dna_profiles_onboarding_profile_id'), 'growth_dna_profiles', ['onboarding_profile_id'], unique=False)
    op.create_index(op.f('ix_growth_dna_profiles_workspace_id'), 'growth_dna_profiles', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_growth_dna_profiles_workspace_id'), table_name='growth_dna_profiles')
    op.drop_index(op.f('ix_growth_dna_profiles_onboarding_profile_id'), table_name='growth_dna_profiles')
    op.drop_table('growth_dna_profiles')
    op.drop_index(op.f('ix_onboarding_profiles_workspace_id'), table_name='onboarding_profiles')
    op.drop_table('onboarding_profiles')
    # ### end Alembic commands ###
