"""seo projects and keywords

Revision ID: 064a8b2cb0cc
Revises: 37dacfd5214b
Create Date: 2026-04-25 23:15:41.131744+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '064a8b2cb0cc'
down_revision: Union[str, None] = '37dacfd5214b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('site_url', sa.String(length=2048), nullable=True),
    sa.Column('search_console_site_url', sa.String(length=2048), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_search_console_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crawl_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_seo_projects_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seo_projects'))
    )
    op.create_index(op.f('ix_seo_projects_workspace_id'), 'seo_projects', ['workspace_id'], unique=True)
    op.create_table('keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seo_project_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('opportunity_score', sa.Integer(), nullable=False),
    sa.Column('top_page', sa.String(length=2048), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seo_project_id'], ['seo_projects.id'], name=op.f('fk_keywords_seo_project_id_seo_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keywords')),
    sa.UniqueConstraint('seo_project_id', 'query', name='uq_keywords_project_query')
    )
    op.create_index(op.f('ix_keywords_seo_project_id'), 'keywords', ['seo_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keywords_seo_project_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_seo_projects_workspace_id'), table_name='seo_projects')
    op.drop_table('seo_projects')
    # ### end Alembic commands ###
