"""recommendation executions

Revision ID: b13c0e5fd672
Revises: a4ef50f08e69
Create Date: 2026-04-26 01:26:00.409419+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b13c0e5fd672'
down_revision: Union[str, None] = 'a4ef50f08e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('approval_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'REVERTED', name='execution_status'), nullable=False),
    sa.Column('target_external_id', sa.String(length=128), nullable=True),
    sa.Column('target_external_account_id', sa.String(length=128), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prior_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_revert', sa.Boolean(), nullable=False),
    sa.Column('reverts_execution_id', sa.UUID(), nullable=True),
    sa.Column('executed_by', sa.UUID(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], name=op.f('fk_recommendation_executions_approval_id_approvals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], name=op.f('fk_recommendation_executions_executed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_recommendation_executions_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reverts_execution_id'], ['recommendation_executions.id'], name=op.f('fk_recommendation_executions_reverts_execution_id_recommendation_executions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_recommendation_executions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_executions'))
    )
    op.create_index(op.f('ix_recommendation_executions_action_type'), 'recommendation_executions', ['action_type'], unique=False)
    op.create_index(op.f('ix_recommendation_executions_provider'), 'recommendation_executions', ['provider'], unique=False)
    op.create_index(op.f('ix_recommendation_executions_recommendation_id'), 'recommendation_executions', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_executions_workspace_id'), 'recommendation_executions', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_executions_workspace_id'), table_name='recommendation_executions')
    op.drop_index(op.f('ix_recommendation_executions_recommendation_id'), table_name='recommendation_executions')
    op.drop_index(op.f('ix_recommendation_executions_provider'), table_name='recommendation_executions')
    op.drop_index(op.f('ix_recommendation_executions_action_type'), table_name='recommendation_executions')
    op.drop_table('recommendation_executions')
    # ### end Alembic commands ###
