"""approvals and audit logs

Revision ID: 0b12476ab2ee
Revises: ce67c12466e5
Create Date: 2026-04-25 21:50:03.298588+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b12476ab2ee'
down_revision: Union[str, None] = 'ce67c12466e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('USER', 'AGENT', 'SYSTEM', name='audit_actor_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_audit_logs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('risk_level', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='recommendation_risk_level', create_type=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXECUTED', 'CANCELED', name='approval_status'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.UUID(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_approvals_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_approvals_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], name=op.f('fk_approvals_rejected_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_approvals_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals')),
    sa.UniqueConstraint('recommendation_id', name=op.f('uq_approvals_recommendation_id'))
    )
    op.create_index(op.f('ix_approvals_workspace_id'), 'approvals', ['workspace_id'], unique=False)
    # ### end Alembic commands ###

    # Backfill: create one pending approval per existing recommendation. Map the
    # recommendation's existing status to an approval status where it makes sense.
    op.execute(
        """
        INSERT INTO approvals (
            id, workspace_id, recommendation_id, action_type, risk_level, status,
            created_at, updated_at
        )
        SELECT
            gen_random_uuid(),
            r.workspace_id,
            r.id,
            r.recommendation_type,
            r.risk_level,
            CASE r.status
                WHEN 'OPEN'     THEN 'PENDING'::approval_status
                WHEN 'APPROVED' THEN 'APPROVED'::approval_status
                WHEN 'REJECTED' THEN 'REJECTED'::approval_status
                WHEN 'EXECUTED' THEN 'EXECUTED'::approval_status
                WHEN 'ARCHIVED' THEN 'CANCELED'::approval_status
                ELSE 'PENDING'::approval_status
            END,
            now(),
            now()
        FROM recommendations r
        WHERE NOT EXISTS (SELECT 1 FROM approvals a WHERE a.recommendation_id = r.id)
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_workspace_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
