"""ab tests

Revision ID: ac766d21a2f2
Revises: 21aaa3e026d2
Create Date: 2026-04-26 02:04:22.405565+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac766d21a2f2'
down_revision: Union[str, None] = '21aaa3e026d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('target', sa.Enum('AD', 'LANDING_PAGE', name='ab_test_target'), nullable=False),
    sa.Column('objective', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'LAUNCHED', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='ab_test_status'), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('external_account_id', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('winner_variant_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ab_tests_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ab_tests_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ab_tests'))
    )
    op.create_index(op.f('ix_ab_tests_status'), 'ab_tests', ['status'], unique=False)
    op.create_index(op.f('ix_ab_tests_workspace_id'), 'ab_tests', ['workspace_id'], unique=False)
    op.create_table('ab_test_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('ab_test_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_control', sa.Boolean(), nullable=False),
    sa.Column('traffic_share', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('launched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ab_test_id'], ['ab_tests.id'], name=op.f('fk_ab_test_variants_ab_test_id_ab_tests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ab_test_variants_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ab_test_variants'))
    )
    op.create_index(op.f('ix_ab_test_variants_ab_test_id'), 'ab_test_variants', ['ab_test_id'], unique=False)
    op.create_index(op.f('ix_ab_test_variants_workspace_id'), 'ab_test_variants', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ab_test_variants_workspace_id'), table_name='ab_test_variants')
    op.drop_index(op.f('ix_ab_test_variants_ab_test_id'), table_name='ab_test_variants')
    op.drop_table('ab_test_variants')
    op.drop_index(op.f('ix_ab_tests_workspace_id'), table_name='ab_tests')
    op.drop_index(op.f('ix_ab_tests_status'), table_name='ab_tests')
    op.drop_table('ab_tests')
    # ### end Alembic commands ###
