"""integrations and oauth

Revision ID: 2e78aa0f30f1
Revises: 0b12476ab2ee
Create Date: 2026-04-25 22:09:01.316885+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e78aa0f30f1'
down_revision: Union[str, None] = '0b12476ab2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connected_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DISCONNECTED', 'CONNECTED', 'ERROR', name='connected_account_status'), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('connected_by', sa.UUID(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connected_by'], ['users.id'], name=op.f('fk_connected_accounts_connected_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_connected_accounts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connected_accounts')),
    sa.UniqueConstraint('workspace_id', 'provider', name='uq_connected_accounts_workspace_provider')
    )
    op.create_index(op.f('ix_connected_accounts_provider'), 'connected_accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_connected_accounts_workspace_id'), 'connected_accounts', ['workspace_id'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connected_account_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connected_account_id'], ['connected_accounts.id'], name=op.f('fk_oauth_tokens_connected_account_id_connected_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_tokens')),
    sa.UniqueConstraint('connected_account_id', name=op.f('uq_oauth_tokens_connected_account_id'))
    )
    op.create_table('sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connected_account_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'FAILED', name='sync_log_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connected_account_id'], ['connected_accounts.id'], name=op.f('fk_sync_logs_connected_account_id_connected_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_logs'))
    )
    op.create_index(op.f('ix_sync_logs_connected_account_id'), 'sync_logs', ['connected_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_logs_connected_account_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_connected_accounts_workspace_id'), table_name='connected_accounts')
    op.drop_index(op.f('ix_connected_accounts_provider'), table_name='connected_accounts')
    op.drop_table('connected_accounts')
    # ### end Alembic commands ###
