"""landing pages

Revision ID: 19f562bef920
Revises: 064a8b2cb0cc
Create Date: 2026-04-25 23:29:25.662032+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19f562bef920'
down_revision: Union[str, None] = '064a8b2cb0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'ONBOARDING', name='landing_page_source'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('last_audited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_audit_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_landing_pages_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_landing_pages')),
    sa.UniqueConstraint('workspace_id', 'url', name='uq_landing_pages_workspace_url')
    )
    op.create_index(op.f('ix_landing_pages_workspace_id'), 'landing_pages', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_landing_pages_workspace_id'), table_name='landing_pages')
    op.drop_table('landing_pages')
    # ### end Alembic commands ###
