"""ab test exposures and conversions

Revision ID: 1f7b282221e6
Revises: 4cadbe751543
Create Date: 2026-04-26 03:05:07.542796+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f7b282221e6'
down_revision: Union[str, None] = '4cadbe751543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_test_conversions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('ab_test_id', sa.UUID(), nullable=False),
    sa.Column('ab_test_variant_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_cents', sa.BigInteger(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ab_test_id'], ['ab_tests.id'], name=op.f('fk_ab_test_conversions_ab_test_id_ab_tests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ab_test_variant_id'], ['ab_test_variants.id'], name=op.f('fk_ab_test_conversions_ab_test_variant_id_ab_test_variants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ab_test_conversions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ab_test_conversions'))
    )
    op.create_index(op.f('ix_ab_test_conversions_ab_test_id'), 'ab_test_conversions', ['ab_test_id'], unique=False)
    op.create_index(op.f('ix_ab_test_conversions_ab_test_variant_id'), 'ab_test_conversions', ['ab_test_variant_id'], unique=False)
    op.create_index(op.f('ix_ab_test_conversions_visitor_id'), 'ab_test_conversions', ['visitor_id'], unique=False)
    op.create_index(op.f('ix_ab_test_conversions_workspace_id'), 'ab_test_conversions', ['workspace_id'], unique=False)
    op.create_table('ab_test_exposures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('ab_test_id', sa.UUID(), nullable=False),
    sa.Column('ab_test_variant_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ab_test_id'], ['ab_tests.id'], name=op.f('fk_ab_test_exposures_ab_test_id_ab_tests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ab_test_variant_id'], ['ab_test_variants.id'], name=op.f('fk_ab_test_exposures_ab_test_variant_id_ab_test_variants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ab_test_exposures_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ab_test_exposures')),
    sa.UniqueConstraint('ab_test_id', 'visitor_id', name='uq_ab_test_exposures_test_visitor')
    )
    op.create_index(op.f('ix_ab_test_exposures_ab_test_id'), 'ab_test_exposures', ['ab_test_id'], unique=False)
    op.create_index(op.f('ix_ab_test_exposures_ab_test_variant_id'), 'ab_test_exposures', ['ab_test_variant_id'], unique=False)
    op.create_index(op.f('ix_ab_test_exposures_visitor_id'), 'ab_test_exposures', ['visitor_id'], unique=False)
    op.create_index(op.f('ix_ab_test_exposures_workspace_id'), 'ab_test_exposures', ['workspace_id'], unique=False)
    # NOTE: alembic autogenerate doesn't see the partial-index WHERE clause
    # added in `4cadbe751543`, so it tries to drop and recreate the
    # idempotency-key index here. We strip both halves — leave it alone.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ab_test_exposures_workspace_id'), table_name='ab_test_exposures')
    op.drop_index(op.f('ix_ab_test_exposures_visitor_id'), table_name='ab_test_exposures')
    op.drop_index(op.f('ix_ab_test_exposures_ab_test_variant_id'), table_name='ab_test_exposures')
    op.drop_index(op.f('ix_ab_test_exposures_ab_test_id'), table_name='ab_test_exposures')
    op.drop_table('ab_test_exposures')
    op.drop_index(op.f('ix_ab_test_conversions_workspace_id'), table_name='ab_test_conversions')
    op.drop_index(op.f('ix_ab_test_conversions_visitor_id'), table_name='ab_test_conversions')
    op.drop_index(op.f('ix_ab_test_conversions_ab_test_variant_id'), table_name='ab_test_conversions')
    op.drop_index(op.f('ix_ab_test_conversions_ab_test_id'), table_name='ab_test_conversions')
    op.drop_table('ab_test_conversions')
    # ### end Alembic commands ###
