"""campaigns

Revision ID: 37dacfd5214b
Revises: 2e78aa0f30f1
Create Date: 2026-04-25 22:20:38.634283+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37dacfd5214b'
down_revision: Union[str, None] = '2e78aa0f30f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('connected_account_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('external_account_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ENDED', 'ARCHIVED', 'UNKNOWN', name='campaign_status'), nullable=False),
    sa.Column('objective', sa.String(length=120), nullable=True),
    sa.Column('daily_budget_cents', sa.BigInteger(), nullable=True),
    sa.Column('lifetime_budget_cents', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connected_account_id'], ['connected_accounts.id'], name=op.f('fk_campaigns_connected_account_id_connected_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_campaigns_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('workspace_id', 'provider', 'external_id', name='uq_campaigns_workspace_provider_external')
    )
    op.create_index(op.f('ix_campaigns_connected_account_id'), 'campaigns', ['connected_account_id'], unique=False)
    op.create_index(op.f('ix_campaigns_provider'), 'campaigns', ['provider'], unique=False)
    op.create_index(op.f('ix_campaigns_workspace_id'), 'campaigns', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_workspace_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_provider'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_connected_account_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
