"""backlink prospects and outreach emails

Revision ID: 21aaa3e026d2
Revises: ca2f859f8819
Create Date: 2026-04-26 01:55:34.203909+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21aaa3e026d2'
down_revision: Union[str, None] = 'ca2f859f8819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backlink_prospects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('page_url', sa.String(length=1024), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_role', sa.String(length=120), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('domain_authority', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'QUEUED', 'CONTACTED', 'REPLIED', 'WON', 'DECLINED', 'BOUNCED', 'ARCHIVED', name='backlink_prospect_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('won_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('backlink_url', sa.String(length=1024), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_backlink_prospects_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_backlink_prospects_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backlink_prospects')),
    sa.UniqueConstraint('workspace_id', 'domain', name='uq_backlink_prospects_workspace_domain')
    )
    op.create_index(op.f('ix_backlink_prospects_contact_email'), 'backlink_prospects', ['contact_email'], unique=False)
    op.create_index(op.f('ix_backlink_prospects_domain'), 'backlink_prospects', ['domain'], unique=False)
    op.create_index(op.f('ix_backlink_prospects_status'), 'backlink_prospects', ['status'], unique=False)
    op.create_index(op.f('ix_backlink_prospects_workspace_id'), 'backlink_prospects', ['workspace_id'], unique=False)
    op.create_table('outreach_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('prospect_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'SCHEDULED', 'SENT', 'FAILED', 'REPLIED', 'BOUNCED', name='outreach_email_status'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_outreach_emails_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_outreach_emails_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prospect_id'], ['backlink_prospects.id'], name=op.f('fk_outreach_emails_prospect_id_backlink_prospects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_outreach_emails_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outreach_emails'))
    )
    op.create_index(op.f('ix_outreach_emails_prospect_id'), 'outreach_emails', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_outreach_emails_status'), 'outreach_emails', ['status'], unique=False)
    op.create_index(op.f('ix_outreach_emails_workspace_id'), 'outreach_emails', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_emails_workspace_id'), table_name='outreach_emails')
    op.drop_index(op.f('ix_outreach_emails_status'), table_name='outreach_emails')
    op.drop_index(op.f('ix_outreach_emails_prospect_id'), table_name='outreach_emails')
    op.drop_table('outreach_emails')
    op.drop_index(op.f('ix_backlink_prospects_workspace_id'), table_name='backlink_prospects')
    op.drop_index(op.f('ix_backlink_prospects_status'), table_name='backlink_prospects')
    op.drop_index(op.f('ix_backlink_prospects_domain'), table_name='backlink_prospects')
    op.drop_index(op.f('ix_backlink_prospects_contact_email'), table_name='backlink_prospects')
    op.drop_table('backlink_prospects')
    # ### end Alembic commands ###
