"""agents and recommendations

Revision ID: ce67c12466e5
Revises: 66e7e6ee9578
Create Date: 2026-04-25 21:31:56.012864+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce67c12466e5'
down_revision: Union[str, None] = '66e7e6ee9578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('agent_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='agent_run_status'), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('token_usage_input', sa.Integer(), nullable=True),
    sa.Column('token_usage_output', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd_micros', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], name=op.f('fk_agent_runs_triggered_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_agent_runs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_agent_type'), 'agent_runs', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_runs_workspace_id'), 'agent_runs', ['workspace_id'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('task_index', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='agent_task_status'), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_agent_tasks_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_tasks'))
    )
    op.create_index(op.f('ix_agent_tasks_agent_run_id'), 'agent_tasks', ['agent_run_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=64), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='recommendation_risk_level'), nullable=False),
    sa.Column('expected_impact', sa.Text(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'APPROVED', 'REJECTED', 'EXECUTED', 'ARCHIVED', name='recommendation_status'), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_recommendations_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_recommendations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_agent_run_id'), 'recommendations', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_recommendations_recommendation_type'), 'recommendations', ['recommendation_type'], unique=False)
    op.create_index(op.f('ix_recommendations_workspace_id'), 'recommendations', ['workspace_id'], unique=False)
    op.create_table('skill_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('agent_task_id', sa.UUID(), nullable=True),
    sa.Column('skill_name', sa.String(length=120), nullable=False),
    sa.Column('output_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_skill_outputs_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_task_id'], ['agent_tasks.id'], name=op.f('fk_skill_outputs_agent_task_id_agent_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_outputs'))
    )
    op.create_index(op.f('ix_skill_outputs_agent_run_id'), 'skill_outputs', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_skill_outputs_agent_task_id'), 'skill_outputs', ['agent_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_outputs_agent_task_id'), table_name='skill_outputs')
    op.drop_index(op.f('ix_skill_outputs_agent_run_id'), table_name='skill_outputs')
    op.drop_table('skill_outputs')
    op.drop_index(op.f('ix_recommendations_workspace_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_recommendation_type'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_agent_run_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_agent_tasks_agent_run_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_agent_runs_workspace_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_type'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
