"""content drafts

Revision ID: ca2f859f8819
Revises: b13c0e5fd672
Create Date: 2026-04-26 01:44:10.759201+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca2f859f8819'
down_revision: Union[str, None] = 'b13c0e5fd672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('BLOG_POST', 'LANDING_PAGE', 'AD_COPY', 'META_DESCRIPTION', 'EMAIL', 'SOCIAL_POST', name='content_draft_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'REJECTED', 'PUBLISHED', 'ARCHIVED', name='content_draft_status'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('target_url', sa.String(length=1024), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seo_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_content_drafts_agent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_content_drafts_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_content_drafts_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_content_drafts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_drafts'))
    )
    op.create_index(op.f('ix_content_drafts_agent_run_id'), 'content_drafts', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_content_drafts_status'), 'content_drafts', ['status'], unique=False)
    op.create_index(op.f('ix_content_drafts_type'), 'content_drafts', ['type'], unique=False)
    op.create_index(op.f('ix_content_drafts_workspace_id'), 'content_drafts', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_drafts_workspace_id'), table_name='content_drafts')
    op.drop_index(op.f('ix_content_drafts_type'), table_name='content_drafts')
    op.drop_index(op.f('ix_content_drafts_status'), table_name='content_drafts')
    op.drop_index(op.f('ix_content_drafts_agent_run_id'), table_name='content_drafts')
    op.drop_table('content_drafts')
    # ### end Alembic commands ###
